<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.81.0" />


<title>Did the 2019 Colorado Rockies really lack pitching talent? - Zachary Everts&#39; GitHub Site</title>
<meta property="og:title" content="Did the 2019 Colorado Rockies really lack pitching talent? - Zachary Everts&#39; GitHub Site">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/rstudio/blogdown">GitHub</a></li>
    
    <li><a href="https://twitter.com/EvertsZachary">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">11 min read</span>
    

    <h1 class="article-title">Did the 2019 Colorado Rockies really lack pitching talent?</h1>

    
    <span class="article-date">2021-04-04</span>
    

    <div class="article-content">
      
<script src="/2021/04/04/did-the-2019-colorado-rockies-really-lack-pitching-talent/index_files/header-attrs/header-attrs.js"></script>


<p>The Colorado Rockies aren’t typically known for their pitching prowess but for their ability to hit. The 2019 season was no exception with the Rockies having statistically one of the worst bullpens. The Rockies gave up the most hits and subsequently had the second-highest ERA in the MLB. For most teams, it would be easy to place all the blame on the pitching staff but the Rockies have a big factor lurking in the altitude of Coors Field.</p>
<p>The Coors field effect is widely known and often attributed to hits flying farther in the thin Colorado air. However, slightly lesser known is the fact that the thin air actually has an effect on pitches break making it harder for pitchers to excel in this park. So I wanted to take a deeper look to see if the Rockies’ 2019 season pitching woes can truly be attributed to the bullpen or if Coors Field is skewing their statistics.</p>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Tm = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<p>I’m going to start by looking at the entire MLB’s pitching statistics and focusing on Hits given up, ERA, and Wins.</p>
<pre class="r"><code>Col &lt;- MLBpitch %&gt;% filter(Tm == &quot;COL&quot;)
LAD &lt;- MLBpitch %&gt;% filter(Tm == &quot;LAD&quot;)

ggplot() + 
  geom_point(data=MLBpitch, aes(x=H, y=W, size = ERA), 
    alpha = .65) + 
  scale_size(range = c(2.5, 9), name=&quot;ERA&quot;)+
  geom_point(
    data = Col,
    aes(x = H, y = W, size = ERA),
    color = &quot;Purple&quot;,
    alpha = .9
  ) + 
  geom_point(
    data = LAD,
    aes(x = H, y = W, size = ERA),
    color = &quot;Blue&quot;,
    alpha = .9
  )+
  geom_hline(yintercept = 80.96667) +
  geom_vline(xintercept = 1401.3) +
  theme_minimal() +
  labs(
    x = &quot;Hits Given Up&quot;,
    y = &quot;Wins&quot;,
    title = &quot;The Dodgers thrived while the Rockies seemingly struggled &quot;,
    subtitle = &quot;Colorado gave up the most hits and had the highest ERA but still won more than similiar teams&quot;,
    caption = &quot;Source: baseball-reference.com | By Zachary Everts&quot;) +
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 10), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    )</code></pre>
<p><img src="/2021/04/04/did-the-2019-colorado-rockies-really-lack-pitching-talent/index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
The Dodgers and Rockies both play in the National League West Division but somehow ended up on opposite ends of the pitching scales. The Dodgers gave up just 3.37 ERA over the course of the season and winning 106 games in the process. Meanwhile, the Rockies gave up a near league-high 5.56 ERA but somewhat surprisingly won 71 games. The Rockies don’t appear to fit within the rest of the model winning more games than teams with similar statistics.</p>
<p>To look further into this oddity in trends I wanted to isolate the pitching statistics at Coors Field vs on the road. To do this I gathered the 2019 season pitching game logs for both the Colorado Rockies and Los Angeles Dodgers and separated them into a home and away ERA splits.</p>
<pre class="r"><code>Col &lt;- read_csv(&quot;ColGame1.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Date = col_character(),
##   Loc = col_character(),
##   Opp = col_character(),
##   Rslt = col_character(),
##   Umpire = col_character(),
##   `Pitchers Used (Rest-GameScore-Dec)` = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<pre class="r"><code>LAD &lt;- read_csv(&quot;LADpitch.csv&quot;)</code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X4&#39; [4]</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   X4 = col_character(),
##   Opp = col_character(),
##   Rslt = col_character(),
##   Umpire = col_character(),
##   `Pitchers Used (Rest-GameScore-Dec)` = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<pre class="r"><code>Home &lt;- Col %&gt;% filter(Loc == &quot;x&quot;) 
Away &lt;- Col %&gt;% filter(Loc == &quot;@&quot;)
Home_LA &lt;- LAD %&gt;% filter(X4 == &quot;x&quot; )
Away_LA &lt;- LAD %&gt;% filter(X4 == &quot;@&quot; )
 
 ERA_A &lt;-Away %&gt;% mutate(
   Runs = cumsum(ER),
   Innings = cumsum(IP),
   Home_Runs = cumsum(HR),
   Doubles = cumsum(`2B`),
   Triples = cumsum(`3B`),
   Hits = cumsum(H),
   a_ERA = ((Runs / Innings) * 9)
 )

   ERA_H &lt;-Home %&gt;% mutate(
   Runs = cumsum(ER),
   Innings = cumsum(IP),
   Home_Runs = cumsum(HR),
   Doubles = cumsum(`2B`),
   Triples = cumsum(`3B`),
   Hits = cumsum(H),
   h_ERA = ((Runs / Innings) * 9)
 )
   
 ERA_A_LA &lt;-Away_LA %&gt;% mutate(
   Runs = cumsum(ER),
   Innings = cumsum(IP),
   a_ERA = ((Runs / Innings) * 9)
 )

   ERA_H_LA &lt;-Home_LA %&gt;% mutate(
   Runs = cumsum(ER),
   Innings = cumsum(IP),
   h_ERA = ((Runs / Innings) * 9)
 )</code></pre>
<pre class="r"><code>splits &lt;- read_csv(&quot;splits.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   Team = col_character(),
##   ERA = col_double(),
##   Rk = col_double()
## )</code></pre>
<pre class="r"><code>split_LA_H &lt;- splits %&gt;% filter(Team == &quot;LAD Home&quot;)
split_LA_A &lt;- splits %&gt;% filter(Team == &quot;LAD Away&quot;)
split_Co_H &lt;- splits %&gt;% filter(Team == &quot;Col Home&quot;)
split_Co_A &lt;- splits %&gt;% filter(Team == &quot;Col Home&quot;)
splits_League &lt;- splits %&gt;% filter(Team == &quot;League Average&quot;)</code></pre>
<pre class="r"><code>set.seed(1234)
  ggplot()+ 
  geom_line(data = ERA_H, aes(x = Rk, y = h_ERA), color = &quot;#881eeb&quot;, size = .79,) + 
  geom_line(data = ERA_A, aes(x = Rk, y = a_ERA), color = &quot;#000000&quot;, size = .79) +
  geom_line(data = ERA_A_LA, aes(x = Rk, y = a_ERA), color = &quot;grey&quot;, size = .79) +
  geom_line(data = ERA_H_LA, aes(x = Rk, y = h_ERA), color = &quot;Blue&quot;, size = .79) +
  geom_text_repel(
    data=split_LA_H, 
    aes(x=Rk, y=ERA, label=&quot;LAD Home&quot;)
  )+
  geom_text_repel(
    data=split_LA_A, 
    aes(x=Rk, y=ERA, label=&quot;LAD Away&quot;)
  )+
  geom_text_repel(
    data=split_Co_H, 
    aes(x=Rk, y=ERA, label=&quot;COL Home&quot;)
  )+
  geom_text_repel(
    data=split_Co_A, 
    aes(x=Rk, y=ERA, label=&quot;Col Away&quot;)
  )+
  geom_text_repel(
  data=splits_League, 
  aes(x=Rk, y=ERA, label=&quot;MLB Average&quot;)
  )+
  geom_hline (yintercept = 4.497, color = &quot;red&quot;) +
    scale_y_continuous(limits = c(0, 10)) +
    labs(y = &quot;ERA&quot;,x = &quot;Game&quot;, 
       title = &quot;Road Struggles vs Home Success&quot;,
       subtitle = &quot;The Rockies pitched better on the road but both splits were higher than the league average ERA&quot;,
       caption = &quot;Source: baseball-reference.com | By Zachary Everts&quot;) +
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(size = 8),
    panel.grid.minor = element_blank()
  )</code></pre>
<p><img src="/2021/04/04/did-the-2019-colorado-rockies-really-lack-pitching-talent/index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The Rockies splits especially at the beginning of the season were drastically different. At Coors Field, Colorado’s ERA was nearly 6.2, while on the road it landed closer to 4.9. Colorado gave up on average 1.3 more runs at home than in opponents’ ballparks. This isn’t even taking into account the possibilities of Home Field advantages. The Dodgers on the other hand pitched better at home with an ERA of 2.8 at home versus 3.95 on the road.</p>
<p>Looking at the season overall for the first half of the season Colorado’s road split was lower than the league average. By the end of the season, however, both of Colorado’s splits were above that mark, which leans towards the assumption of Colorado having a sub-par pitching staff. The sizable difference between the home and road splits does however suggest that Coors Field is affecting their stat line.</p>
<p>To see what could be causing this difference I will decide to look at the correlation between hits given up and ERA using Colorado’s 2019 game logs.</p>
<pre class="r"><code>Correlation &lt;-Col %&gt;% 
  mutate(
    era = ((ER/IP) *9)
  )</code></pre>
<pre class="r"><code>Correlation %&gt;% 
  summarize(Correlation = cor(`H`, era, method = &#39;pearson&#39;))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   Correlation
##         &lt;dbl&gt;
## 1       0.765</code></pre>
<pre class="r"><code>fit &lt;- lm(era ~ H, data = Correlation)

summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = era ~ H, data = Correlation)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.8299 -1.8631 -0.1242  1.6064  8.3924 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.57598    0.51879  -3.038  0.00278 ** 
## H            0.74447    0.04957  15.017  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.434 on 160 degrees of freedom
## Multiple R-squared:  0.585,  Adjusted R-squared:  0.5824 
## F-statistic: 225.5 on 1 and 160 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>Correlation$predicted &lt;- predict(fit)

Correlation$residuals &lt;- residuals(fit) </code></pre>
<p>It almost goes without saying but there is a strong correlation between the number of hits a pitcher allows and their subsequent ERA’s. I mean, you can’t score without hitting the ball. According to my correlation, 58% of all ERA’s can be predicted using hits to determine ERA. I’m going to use this correlation to create a model that will predict Colorado’s ERA based on hits allowed per game.</p>
<pre class="r"><code>Correlation %&gt;% 
  arrange(desc(residuals)) %&gt;% 
  select(Opp, Rslt, era, H, residuals, predicted)</code></pre>
<pre><code>## # A tibble: 162 x 6
##    Opp   Rslt      era     H residuals predicted
##    &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 HOU   L,3-14   15.8    12      8.39      7.36
##  2 LAD   L,5-12   13.5    13      5.40      8.10
##  3 SDP   L,13-14  14      15      4.41      9.59
##  4 HOU   L,6-11   12.4    13      4.27      8.10
##  5 CHC   L,8-9    10.1    10      4.26      5.87
##  6 SDP   W,11-10  10      10      4.13      5.87
##  7 SFG   L,2-19   18      21      3.94     14.1 
##  8 PIT   L,6-14   13.5    15      3.91      9.59
##  9 SFG   W,12-11   9       9      3.88      5.12
## 10 ARI   L,0-8     9       9      3.88      5.12
## # … with 152 more rows</code></pre>
<pre class="r"><code>Home = Correlation %&gt;% filter(Loc == &quot;x&quot;)

ggplot(Correlation, aes(x=H, y=era)) + 
  geom_point(color = &quot;grey&quot;)+
  geom_smooth(method=lm, se=TRUE)+
  geom_point(data = Home, aes(x=H, y=era), color = &quot;purple&quot;) +
    labs(y = &quot;ERA&quot;, 
         x = &quot;Hits&quot;,
       title = &quot;The Rockies 2019 season exemplified a strong correlation between Hits and ERA&quot;,
       subtitle = &quot;The Rockies often overperformed at home compared to the nubmer of hits given up&quot;, 
caption = &quot;Source: baseball-reference.com | By Zachary Everts&quot;) +
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 12, face = &quot;bold&quot;),
    plot.subtitle = element_text(size = 10),
    axis.title = element_text(size = 8),
    panel.grid.minor = element_blank()
  )</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/2021/04/04/did-the-2019-colorado-rockies-really-lack-pitching-talent/index_files/figure-html/unnamed-chunk-13-1.png" width="672" />
This graph further shows the strong positive correlation between hits and ERA. The purple dots on the graph represent home games while grey represents games on the road. Using this model I can predict a game’s outcome-based off of the number of hits allowed. This model shows that Colorado actually slightly over-performed in a good chunk of home games, with more of those purple dots falling below the line than above. The interesting thing is that many of these performances still fall within a significantly high ERA range between 5-10. Colorado seems to give up many more hits at Coors Field.</p>
<pre class="r"><code>(.74447 * 4) -1.57598 #Plug in number of hits to predict ERA</code></pre>
<pre><code>## [1] 1.4019</code></pre>
<p>This model can be used to predict a team’s ERA based off of the number of hits allowed. For example, if the Rockies had given up four hits in a game, the model predicts that the ERA would’ve been close to 1.4. I’m going to use this model to predict what the Rockies season ERA would’ve been if they played all of their games away from Coors Field. But first, let’s take a look at Colorado’s home and away splits.</p>
<pre class="r"><code>col_Ab &lt;- c(&quot;Singles&quot; = 414, &quot;Extra-base hits&quot; = 151,  &quot;Home Runs&quot; = 126, 194)
col_Hb &lt;- c(&quot;Singles&quot; = 523, &quot;Extra-base hits&quot; = 218,  &quot;Home Runs&quot; = 144)</code></pre>
<pre class="r"><code>iron(
waffle(
  col_Hb/3,
  rows = 9,
  title = &quot;The Rockies couldn&#39;t limit the number of hits allowed at home&quot;,
  xlab = &quot;1 square = 3 occurences&quot;,
  colors = c(&quot;#881eeb&quot;, &quot;#C4CED4&quot;, &quot;#27251F&quot;), 
) +theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    ),
waffle(
  col_Ab/3,
  rows = 9,
  title = &quot;Colorado excelled at pitching on the road&quot;,
  xlab = &quot;1 square = 3 occurences&quot;,
  colors = c(&quot;#881eeb&quot;,  &quot;#C4CED4&quot;, &quot;#27251F&quot;, &quot;White&quot;)
) +theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    ) 
)</code></pre>
<p><img src="/2021/04/04/did-the-2019-colorado-rockies-really-lack-pitching-talent/index_files/figure-html/unnamed-chunk-16-1.png" width="672" />
Colorado gave up fewer hits on the road in every single category during the 2019 season. In total there were 194 more hits given up by Rockies pitchers at Coors Field than playing on the road.</p>
<p>On the road, Colorado gave up 691 hits over the course of the season. Since half of Colorado’s games were played at home I multiplied this number by two to get 1382 hits. I then was able to find hits per game by dividing total hits by the number of games played. This resulted in 8.53 hits per game.</p>
<pre class="r"><code>(.74447 * 8.53) -1.57598 #Plug in number of hits to predict ERA</code></pre>
<pre><code>## [1] 4.774349</code></pre>
<pre class="r"><code>(.74447 * 10.93) -1.57598 #Plug in number of hits to predict ERA</code></pre>
<pre><code>## [1] 6.561077</code></pre>
<p>Plugging that number into our model results in a season ERA of 4.77 which is just barely higher than the MLB average of 4.497. Repeating this process with home games at Coors Field resulted in a season ERA of 6.56, which would be by far the highest team ERA in the MLB. At this point, it’s safe to say that Coors Field has a significant effect on Colorado’s pitching performances.</p>
<p>The interesting thing is that even though the Rockies pitchers perform better on the road, the team wins at a much higher clip at home. In 2019 Colorado went (43-38) at Coors Field and (28-53) on the road. So even with better pitching numbers on the road they still struggle to win. This is most likely attributed to Colorado’s batting woes away from home but could also be attributed to the pitching.</p>
<p>Colorado’s road pitching numbers aren’t even very good. Looking at the model’s ERA prediction for Colorado playing only road games, a 4.77 ERA, the Rockies would still have the 11th worst ERA in the MLB. This goes to show that the Rockies are indeed lacking pitching talent. Coors Field does significantly impact the pitching statistics, but Colorado still has a lack of top-tier pitching talent and an inability to win games on the rood.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

